clear
evalin('base', 'Code_Gen_Model_data');

CPPFileID = fopen('..\src\main\cpp\SimulinkSmartDashboard.cpp', 'w');
HFileID = fopen('..\src\main\include\SimulinkSmartDashboard.h', 'w');
if CPPFileID == -1
    error('Could not open .cpp file for writing');
end
if HFileID == -1
    error('Could not open .h file for writing');
end


HFileContents = {...
    '#include <frc/smartdashboard/SmartDashboard.h>',...
    '#include <networktables/NetworkTable.h>',...
    '#include <networktables/RawTopic.h>',...
    '#include <networktables/NetworkTableInstance.h>',...
    '#include "Code_Gen_Model_ert_rtw\Code_Gen_Model.h"',...
    ' ',...
    'class SimulinkSmartDashboard {',...
    '    public:',...
    '        void InitTunableSmartDashboard();',...
    '    private:',...
    '};'
    };
CPPFileContents = {...
    '#include "include/SimulinkSmartDashboard.h"',...
    ' ',...
    'void SimulinkSmartDashboard::InitTunableSmartDashboard() {}',...
    };


for i = 1:length(CPPFileContents)
    fprintf(CPPFileID, '%s\n', CPPFileContents{i});
end

for i = 1:length(HFileContents)
    fprintf(HFileID, '%s\n', HFileContents{i});
end
% Close the file
fclose(CPPFileID);
fclose(HFileID);

clear HFileID HFileContents CPPFileID CPPFileContents

generate_controller_code;